/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WitPolyRepoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "addCollaborator"
      | "collaborators"
      | "createRepo"
      | "hasAccess"
      | "initialize"
      | "owner"
      | "proxiableUUID"
      | "removeCollaborator"
      | "renounceOwnership"
      | "repositories"
      | "transferOwnership"
      | "updateHead"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CollaboratorAdded"
      | "CollaboratorRemoved"
      | "HeadUpdated"
      | "Initialized"
      | "OwnershipTransferred"
      | "RepositoryCreated"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addCollaborator",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collaborators",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createRepo",
    values: [string, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeCollaborator",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repositories",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateHead",
    values: [BigNumberish, string, string, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCollaborator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collaborators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createRepo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCollaborator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repositories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateHead", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace CollaboratorAddedEvent {
  export type InputTuple = [repoId: BigNumberish, user: AddressLike];
  export type OutputTuple = [repoId: bigint, user: string];
  export interface OutputObject {
    repoId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollaboratorRemovedEvent {
  export type InputTuple = [repoId: BigNumberish, user: AddressLike];
  export type OutputTuple = [repoId: bigint, user: string];
  export interface OutputObject {
    repoId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeadUpdatedEvent {
  export type InputTuple = [
    repoId: BigNumberish,
    newVersion: BigNumberish,
    commitCid: string
  ];
  export type OutputTuple = [
    repoId: bigint,
    newVersion: bigint,
    commitCid: string
  ];
  export interface OutputObject {
    repoId: bigint;
    newVersion: bigint;
    commitCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepositoryCreatedEvent {
  export type InputTuple = [
    repoId: BigNumberish,
    owner: AddressLike,
    name: string
  ];
  export type OutputTuple = [repoId: bigint, owner: string, name: string];
  export interface OutputObject {
    repoId: bigint;
    owner: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WitPolyRepo extends BaseContract {
  connect(runner?: ContractRunner | null): WitPolyRepo;
  waitForDeployment(): Promise<this>;

  interface: WitPolyRepoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  addCollaborator: TypedContractMethod<
    [repoId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  collaborators: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  createRepo: TypedContractMethod<
    [name: string, description: string, isPrivate: boolean],
    [bigint],
    "nonpayable"
  >;

  hasAccess: TypedContractMethod<
    [repoId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  removeCollaborator: TypedContractMethod<
    [repoId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repositories: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        boolean,
        string,
        bigint,
        string,
        string,
        string,
        string,
        string
      ] & {
        id: bigint;
        name: string;
        description: string;
        isPrivate: boolean;
        owner: string;
        version: bigint;
        headCommitCid: string;
        headManifestCid: string;
        headQuiltId: string;
        rootHash: string;
        parentCommitCid: string;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateHead: TypedContractMethod<
    [
      repoId: BigNumberish,
      newCommitCid: string,
      newManifestCid: string,
      newQuiltId: string,
      newRootHash: string,
      expectedVersion: BigNumberish,
      parentCommitCid: string
    ],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addCollaborator"
  ): TypedContractMethod<
    [repoId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collaborators"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "createRepo"
  ): TypedContractMethod<
    [name: string, description: string, isPrivate: boolean],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [repoId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeCollaborator"
  ): TypedContractMethod<
    [repoId: BigNumberish, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repositories"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        boolean,
        string,
        bigint,
        string,
        string,
        string,
        string,
        string
      ] & {
        id: bigint;
        name: string;
        description: string;
        isPrivate: boolean;
        owner: string;
        version: bigint;
        headCommitCid: string;
        headManifestCid: string;
        headQuiltId: string;
        rootHash: string;
        parentCommitCid: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateHead"
  ): TypedContractMethod<
    [
      repoId: BigNumberish,
      newCommitCid: string,
      newManifestCid: string,
      newQuiltId: string,
      newRootHash: string,
      expectedVersion: BigNumberish,
      parentCommitCid: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "CollaboratorAdded"
  ): TypedContractEvent<
    CollaboratorAddedEvent.InputTuple,
    CollaboratorAddedEvent.OutputTuple,
    CollaboratorAddedEvent.OutputObject
  >;
  getEvent(
    key: "CollaboratorRemoved"
  ): TypedContractEvent<
    CollaboratorRemovedEvent.InputTuple,
    CollaboratorRemovedEvent.OutputTuple,
    CollaboratorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "HeadUpdated"
  ): TypedContractEvent<
    HeadUpdatedEvent.InputTuple,
    HeadUpdatedEvent.OutputTuple,
    HeadUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RepositoryCreated"
  ): TypedContractEvent<
    RepositoryCreatedEvent.InputTuple,
    RepositoryCreatedEvent.OutputTuple,
    RepositoryCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "CollaboratorAdded(uint256,address)": TypedContractEvent<
      CollaboratorAddedEvent.InputTuple,
      CollaboratorAddedEvent.OutputTuple,
      CollaboratorAddedEvent.OutputObject
    >;
    CollaboratorAdded: TypedContractEvent<
      CollaboratorAddedEvent.InputTuple,
      CollaboratorAddedEvent.OutputTuple,
      CollaboratorAddedEvent.OutputObject
    >;

    "CollaboratorRemoved(uint256,address)": TypedContractEvent<
      CollaboratorRemovedEvent.InputTuple,
      CollaboratorRemovedEvent.OutputTuple,
      CollaboratorRemovedEvent.OutputObject
    >;
    CollaboratorRemoved: TypedContractEvent<
      CollaboratorRemovedEvent.InputTuple,
      CollaboratorRemovedEvent.OutputTuple,
      CollaboratorRemovedEvent.OutputObject
    >;

    "HeadUpdated(uint256,uint64,string)": TypedContractEvent<
      HeadUpdatedEvent.InputTuple,
      HeadUpdatedEvent.OutputTuple,
      HeadUpdatedEvent.OutputObject
    >;
    HeadUpdated: TypedContractEvent<
      HeadUpdatedEvent.InputTuple,
      HeadUpdatedEvent.OutputTuple,
      HeadUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RepositoryCreated(uint256,address,string)": TypedContractEvent<
      RepositoryCreatedEvent.InputTuple,
      RepositoryCreatedEvent.OutputTuple,
      RepositoryCreatedEvent.OutputObject
    >;
    RepositoryCreated: TypedContractEvent<
      RepositoryCreatedEvent.InputTuple,
      RepositoryCreatedEvent.OutputTuple,
      RepositoryCreatedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
